### ISSUE TITLE
Fix the game scoring and conditional draw of a third card

### ISSUE THREAD

**Issue by bryce-carson** [koddyrae/Assignment-1-COMP1502#11]
https://github.com/koddyrae/Assignment-1-COMP1502/blob/ba303a53be8dd90bbded5fc8b204839cb05a75a4/Assignment%201%20-%20Skeleton/src/mru/game/controller/PuntoBancoGame.java#L44-L108

There is a huge issue here. The large conditional block runs twice, once for each seat, but `seat` is only used in the smaller branch. It makes more sense to refactor this and barf out the larger condition, since it _needs_ to run in all cases where _either_ hand is not 8 or 9.

I will do this.

**Comment by koddyrae** [comment]
okay sounds good tell me when its done so i can go learn whats doing again

**Comment by bryce-carson** [comment]
@koddyrae I'll let you know, yup!
