### ISSUE TITLE
Player's score is referenced when the banker's score is needed

### ISSUE THREAD

**Issue by bryce-carson** [koddyrae/Assignment-1-COMP1502#9]
https://github.com/koddyrae/Assignment-1-COMP1502/blob/ba303a53be8dd90bbded5fc8b204839cb05a75a4/Assignment%201%20-%20Skeleton/src/mru/game/view/AppMenu.java#L258

This line should have `banker.getScore()`; the line previous uses the player's score to print the player's score, while this line needs to print the banker's score.

**Comment by koddyrae** [comment]
thanks didnt notice that
